### ISSUE TITLE
Failing CUDA testing with Nvidia GPU

### ISSUE THREAD

**Issue by russelljjarvis** [SpikingNetwork/TrainSpikingNet.jl#2]
(base) rjjarvis@pop-os:~/git/TrainSpikingNet.jl/test$ julia --project=@. runtests.jl
Array
ERROR: LoadError: CUDA error (code 804, CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE)
Stacktrace:
  [1] throw_api_error(res::CUDA.cudaError_enum)
    @ CUDA ~/.julia/packages/CUDA/BbliS/lib/cudadrv/error.jl:89
  [2] macro expansion
    @ ~/.julia/packages/CUDA/BbliS/lib/cudadrv/error.jl:97 [inlined]
  [3] cuInit
    @ ~/.julia/packages/CUDA/BbliS/lib/utils/call.jl:26 [inlined]
  [4] __init_driver__()
    @ CUDA ~/.julia/packages/CUDA/BbliS/src/initialization.jl:84
  [5] libcuda()
    @ CUDA ~/.julia/packages/CUDA/BbliS/lib/cudadrv/CUDAdrv.jl:142
  [6] macro expansion
    @ ~/.julia/packages/CUDA/BbliS/lib/cudadrv/libcuda.jl:29 [inlined]
  [7] macro expansion
    @ ~/.julia/packages/CUDA/BbliS/lib/cudadrv/error.jl:95 [inlined]
  [8] cuDeviceGet
    @ ~/.julia/packages/CUDA/BbliS/lib/utils/call.jl:26 [inlined]
  [9] CuDevice
    @ ~/.julia/packages/CUDA/BbliS/lib/cudadrv/devices.jl:17 [inlined]
 [10] CUDA.TaskLocalState()
    @ CUDA ~/.julia/packages/CUDA/BbliS/lib/cudadrv/state.jl:50
 [11] task_local_state!()
    @ CUDA ~/.julia/packages/CUDA/BbliS/lib/cudadrv/state.jl:73
 [12] active_state
    @ ~/.julia/packages/CUDA/BbliS/lib/cudadrv/state.jl:106 [inlined]
 [13] #_alloc#174
    @ ~/.julia/packages/CUDA/BbliS/src/pool.jl:400 [inlined]
 [14] #alloc#173
    @ ~/.julia/packages/CUDA/BbliS/src/pool.jl:389 [inlined]
 [15] alloc
    @ ~/.julia/packages/CUDA/BbliS/src/pool.jl:383 [inlined]
 [16] CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}(#unused#::UndefInitializer, dims::Tuple{Int64})
    @ CUDA ~/.julia/packages/CUDA/BbliS/src/array.jl:42
 [17] CuArray
    @ ~/.julia/packages/CUDA/BbliS/src/array.jl:291 [inlined]
 [18] CuArray
    @ ~/.julia/packages/CUDA/BbliS/src/array.jl:296 [inlined]
 [19] (CuArray{Float64})(xs::Vector{Float64})
    @ CUDA ~/.julia/packages/CUDA/BbliS/src/array.jl:303
 [20] top-level scope
    @ ~/git/TrainSpikingNet.jl/src/gpu/variables.jl:3
 [21] include(fname::String)
    @ Base.MainInclude ./client.jl:476
 [22] top-level scope
    @ ~/git/TrainSpikingNet.jl/src/gpu/train.jl:90
in expression starting at /home/rjjarvis/git/TrainSpikingNet.jl/src/gpu/variables.jl:3
in expression starting at /home/rjjarvis/git/TrainSpikingNet.jl/src/gpu/train.jl:90
Array: Error During Test at /home/rjjarvis/git/TrainSpikingNet.jl/test/runtests.jl:61
  Got exception outside of a @test
  failed process: Process(`/home/rjjarvis/.julia/juliaup/julia-1.8.5+0.x64.linux.gnu/bin/julia -Cnative -J/home/rjjarvis/.julia/juliaup/julia-1.8.5+0.x64.linux.gnu/lib/julia/sys.so -g1 /home/rjjarvis/git/TrainSpikingNet.jl/test/../src/gpu/train.jl --nloops 1 --correlation_interval 1 /home/rjjarvis/git/TrainSpikingNet.jl/test/scratch/gpu-Array`, ProcessExited(1)) [1]
  
  Stacktrace:
    [1] pipeline_error
      @ ./process.jl:565 [inlined]
    [2] (::Base.var"#732#733"{Base.Process})()
      @ Base ./process.jl:342
    [3] iterate(itr::Base.EachLine{Base.PipeEndpoint}, state::Nothing)
      @ Base ./io.jl:1062
    [4] _collect(cont::UnitRange{Int64}, itr::Base.EachLine{Base.PipeEndpoint}, #unused#::Base.HasEltype, isz::Base.SizeUnknown)
      @ Base ./array.jl:725
    [5] collect
      @ ./array.jl:712 [inlined]
    [6] #readlines#401
      @ ./io.jl:588 [inlined]
    [7] readlines
      @ ./io.jl:588 [inlined]
    [8] compare_cpu_to_gpu(kind::String; ntasks::Int64, nloops::Int64, cinterval::Int64, spikerate::Bool, Pmatrix::Bool, weights::Bool, correlation::Nothing)
      @ Main ~/git/TrainSpikingNet.jl/test/runtests.jl:22
    [9] compare_cpu_to_gpu(kind::String)
      @ Main ~/git/TrainSpikingNet.jl/test/runtests.jl:3
   [10] macro expansion
      @ ~/git/TrainSpikingNet.jl/test/runtests.jl:75 [inlined]
   [11] top-level scope
      @ ~/.julia/juliaup/julia-1.8.5+0.x64.linux.gnu/share/julia/stdlib/v1.8/Test/src/Test.jl:1439
   [12] include(mod::Module, _path::String)
      @ Base ./Base.jl:419
   [13] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:303
   [14] _start()
      @ Base ./client.jl:522
Test Summary: | Pass  Error  Total   Time
Array         |    2      1      3  51.2s
Test Summary: | Pass  Error  Total   Time
Array         |    2      1      3  51.3s
ERROR: LoadError: Some tests did not pass: 2 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/rjjarvis/git/TrainSpikingNet.jl/test/runtests.jl:61

caused by: Some tests did not pass: 2 passed, 0 failed, 1 errored, 0 broken.
(base) rjjarvis@pop-os:~/git/TrainSpikingNet.jl/test$

**Comment by russelljjarvis** [comment]
I often have to do 

```rm -r scratch```

Between re-running of unit tests. I wonder if there is a way to make Julia clean out the scratch directories on a restart of unit testing?

**Comment by mkitti** [comment]
There is  https://github.com/JuliaPackaging/Scratch.jl

**Comment by bjarthur** [comment]
do CUDA.jl's tests pass?  that is, if you cd into the trainspikingnet directory, and then from the julia REPL do `] test CUDA`, are any errors thrown?

and as always with any bug report, it's helpful to know what OS you're using, what version of julia, which graphics card, etc.

**Comment by mkitti** [comment]
> if you cd into the trainspikingnet directory

Did you mean to activate a project in that directory?

**Comment by russelljjarvis** [comment]
> do CUDA.jl's tests pass? that is, if you cd into the trainspikingnet directory, and then from the julia REPL do `] test CUDA`, are any errors thrown?
> 
> and as always with any bug report, it's helpful to know what OS you're using, what version of julia, which graphics card, etc.

 I did do some of `Pkg.test("CUDA")`, but unfortunately I quit before all the tests were completed, I will redo that today and put the update here. I have two Nvidia-compliant Linux environments I can test on.

**Comment by russelljjarvis** [comment]
> > if you cd into the trainspikingnet directory
> 
> Did you mean to activate a project in that directory?

I believe I followed the README.md instructions faithfully which included CC'ing in to TrainingSpikingNet, I will start from scratch again just in case it is human error.

**Comment by russelljjarvis** [comment]
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading.
     Testing Running tests...
┌ Info: System information:
│ CUDA runtime 11.8, artifact installation
│ CUDA driver 12.0
│ NVIDIA driver 525.85.5
│ 
│ Libraries: 
│ - CUBLAS: 11.11.3
│ - CURAND: 10.3.0
│ - CUFFT: 10.9.0
│ - CUSOLVER: 11.4.1
│ - CUSPARSE: 11.7.5
│ - CUPTI: 18.0.0
│ - NVML: 12.0.0+525.85.5
│ 
│ Toolchain:
│ - Julia: 1.8.5
│ - LLVM: 13.0.1
│ - PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2
│ - Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86
│ 
│ 1 device:
└   0: NVIDIA GeForce RTX 2060 (sm_75, 5.469 GiB / 6.000 GiB available)
[ Info: Testing using 1 device(s): 0. NVIDIA GeForce RTX 2060 (UUID eb824920-8fd0-628b-e54f-18a923cf47da)
                                                  |          | ---------------- GPU ---------------- | ---------------- CPU ---------------- |
Test                                     (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB) | GC (s) | GC % | Alloc (MB) | RSS (MB) |
initialization                                (2) |    13.12 |   0.00 |  0.0 |       0.00 |   114.00 |   0.01 |  0.1 |      83.90 |  1276.27 |
gpuarrays/interface                           (2) |    23.56 |   0.00 |  0.0 |       0.00 |   124.00 |   0.63 |  2.7 |    1621.26 |  1276.27 |
gpuarrays/indexing scalar                     (3) |    59.63 |   0.04 |  0.1 |       0.01 |   124.00 |   1.67 |  2.8 |    4637.92 |  1321.11 |
gpuarrays/indexing find                       (8) |    65.46 |   0.04 |  0.1 |       0.13 |   124.00 |   2.58 |  3.9 |    5710.94 |  1273.25 |
gpuarrays/reductions/any all count            (2) |    40.35 |   0.00 |  0.0 |       0.00 |   124.00 |   2.87 |  7.1 |    5212.68 |  1276.27 |
gpuarrays/uniformscaling                      (8) |    21.19 |   0.00 |  0.0 |       0.01 |   124.00 |   0.64 |  3.0 |    1650.12 |  1273.25 |
gpuarrays/math/intrinsics                     (8) |    10.95 |   0.00 |  0.0 |       0.00 |   124.00 |   0.34 |  3.1 |     996.21 |  1273.25 |
gpuarrays/indexing multidimensional           (9) |   107.49 |   0.04 |  0.0 |       1.21 |   124.00 |   3.79 |  3.5 |    9405.62 |  1276.08 |
gpuarrays/math/power                          (6) |   135.72 |   0.04 |  0.0 |       0.01 |   316.00 |   7.83 |  5.8 |   13752.26 |  1618.85 |
gpuarrays/linalg/mul!/vector-matrix           (7) |   172.34 |   0.05 |  0.0 |       0.02 |   316.00 |   6.57 |  3.8 |   15520.17 |  1594.95 |
gpuarrays/reductions/reducedim!               (4) |   225.86 |   0.04 |  0.0 |       1.03 |   124.00 |  14.17 |  6.3 |   24250.70 |  1281.60 |
gpuarrays/constructors                        (7) |    69.28 |   0.01 |  0.0 |       0.65 |   124.00 |   2.18 |  3.1 |    5707.15 |  1644.05 |
gpuarrays/random                              (4) |    48.72 |   0.00 |  0.0 |       0.03 |   124.00 |   1.85 |  3.8 |    4763.57 |  1329.65 |
gpuarrays/statistics                          (9) |   170.44 |   0.01 |  0.0 |       1.51 |   318.00 |   9.54 |  5.6 |   17131.24 |  2082.03 |
gpuarrays/base                                (7) |    65.22 |   0.00 |  0.0 |       8.90 |   124.00 |   3.46 |  5.3 |    6759.21 |  1746.52 |
gpuarrays/linalg                              (5) |   315.15 |   0.05 |  0.0 |      12.73 |   318.00 |  11.91 |  3.8 |   29868.73 |  2273.16 |
gpuarrays/linalg/mul!/matrix-matrix           (2) |   260.64 |   0.02 |  0.0 |       0.12 |   318.00 |   8.77 |  3.4 |   22917.07 |  2058.20 |
gpuarrays/reductions/== isequal               (4) |   150.84 |   0.01 |  0.0 |       1.07 |   124.00 |   7.37 |  4.9 |   16978.97 |  1829.27 |
apiutils                                      (4) |     0.20 |   0.00 |  0.0 |       0.00 |   114.00 |   0.00 |  0.0 |       0.81 |  1829.47 |
gpuarrays/linalg/norm                         (8) |   409.03 |   0.02 |  0.0 |       0.02 |   320.00 |  21.37 |  5.2 |   39614.47 |  3644.70 |
gpuarrays/reductions/mapreduce                (6) |   394.01 |   0.01 |  0.0 |       1.81 |   126.00 |  20.35 |  5.2 |   40573.62 |  2004.87 |
codegen                                       (6) |    19.80 |   0.00 |  0.0 |       0.00 |   170.00 |   0.75 |  3.8 |    1527.38 |  2006.37 |
broadcast                                     (8) |    44.29 |   0.00 |  0.0 |       0.00 |   124.00 |   1.84 |  4.2 |    3728.09 |  3644.79 |
cudadrv                                       (8) |    16.04 |   0.00 |  0.0 |       0.00 |   126.00 |   0.36 |  2.2 |     811.59 |  3644.79 |
gpuarrays/reductions/mapreducedim!            (7) |   267.17 |   0.01 |  0.0 |       1.54 |   126.00 |  16.21 |  6.1 |   27853.16 |  2194.25 |
curand                                        (7) |     0.87 |   0.00 |  0.0 |       0.00 |   122.00 |   0.03 |  3.4 |      34.35 |  2194.25 |
gpuarrays/reductions/minimum maximum extrema  (3) |   528.42 |   0.02 |  0.0 |       2.19 |   128.00 |  31.57 |  6.0 |   56866.19 |  2329.34 |
array                                         (4) |   169.68 |   0.01 |  0.0 |    1264.20 |  1282.00 |   7.07 |  4.2 |   15359.21 |  3337.66 |
gpuarrays/reductions/reduce                   (5) |   292.68 |   0.02 |  0.0 |       1.21 |   126.00 |  16.46 |  5.6 |   30087.06 |  2476.64 |
cufft                                         (8) |    48.46 |   0.01 |  0.0 |     144.27 |   268.00 |   4.78 |  9.9 |    3077.53 |  3678.91 |
iterator                                      (8) |     3.79 |   0.00 |  0.0 |       1.93 |   146.00 |   0.11 |  2.8 |     409.59 |  3679.06 |
      From worker 5:	WARNING: Method definition #3111#kernel(Any) in module Main at /home/rjjarvis/.julia/packages/CUDA/ZdCxS/test/execution.jl:321 overwritten at /home/rjjarvis/.julia/packages/CUDA/ZdCxS/test/execution.jl:329.
linalg                                        (8) |    58.10 |   0.00 |  0.0 |       9.03 |   204.00 |   3.36 |  5.8 |    6372.66 |  3887.63 |
nvml                                          (8) |     0.71 |   0.00 |  0.0 |       0.00 |   146.00 |   0.00 |  0.0 |      30.33 |  3887.63 |
pointer                                       (8) |     0.47 |   0.00 |  0.0 |       0.00 |   146.00 |   0.00 |  0.0 |      11.60 |  3887.63 |
cusparse                                      (7) |   113.94 |   0.04 |  0.0 |       9.47 |   244.00 |   3.30 |  2.9 |    7816.79 |  2604.41 |
pool                                          (8) |     3.86 |   0.00 |  0.0 |       0.00 |   114.00 |   1.49 | 38.7 |     199.69 |  3887.63 |
execution                                     (5) |   131.42 |   0.00 |  0.0 |       0.37 |   174.00 |   4.61 |  3.5 |   10193.72 |  2648.52 |
exceptions                                    (4) |   146.88 |   0.00 |  0.0 |       0.00 |  1266.00 |   0.00 |  0.0 |      15.66 |  3337.66 |
threading                                     (4) |     7.09 |   0.00 |  0.0 |      10.94 |  1480.00 |   0.37 |  5.2 |     517.72 |  3337.66 |
utils                                         (4) |     1.25 |   0.00 |  0.0 |       0.00 |  1266.00 |   0.00 |  0.0 |      75.74 |  3337.66 |
random                                        (7) |    66.32 |   0.00 |  0.0 |     257.15 |   386.00 |   2.65 |  4.0 |    5542.79 |  2700.09 |
cusolver/multigpu                             (7) |    14.55 |   0.00 |  0.0 |     545.90 |   646.00 |   0.34 |  2.3 |     920.84 |  3069.55 |
cusolver/sparse                               (7) |    11.52 |   0.00 |  0.0 |       0.18 |   526.00 |   0.19 |  1.7 |     449.80 |  3153.20 |
examples                                      (3) |   204.72 |   0.00 |  0.0 |       0.00 |   114.00 |   0.00 |  0.0 |      32.54 |  2329.60 |
gpuarrays/reductions/sum prod                 (2) |   474.83 |   0.02 |  0.0 |       3.24 |   128.00 |  24.50 |  5.2 |   47328.82 |  3091.09 |
cusparse/conversions                          (3) |    23.16 |   0.00 |  0.0 |       1.43 |   192.00 |   0.79 |  3.4 |    1986.74 |  2561.48 |
cublas                                        (6) |   266.10 |   0.04 |  0.0 |      14.57 |   330.00 |   8.96 |  3.4 |   19876.90 |  3338.67 |
cusparse/device                               (2) |     2.26 |   0.00 |  0.0 |       0.01 |   192.00 |   0.05 |  2.1 |     105.63 |  3093.35 |
      From worker 6:	WARNING: using CUSPARSE.axpby! in module Main conflicts with an existing identifier.
texture                                       (5) |    90.62 |   0.00 |  0.0 |       0.09 |   128.00 |   4.10 |  4.5 |    8706.53 |  2860.73 |
device/array                                  (5) |    12.34 |   0.00 |  0.0 |       0.00 |   124.00 |   0.46 |  3.8 |    1135.38 |  2860.73 |
cusparse/broadcast                            (7) |    90.66 |   0.00 |  0.0 |       0.02 |   448.00 |   3.78 |  4.2 |    8609.38 |  3288.11 |
gpuarrays/broadcasting                        (9) |   609.26 |   0.02 |  0.0 |       2.00 |   128.00 |  25.83 |  4.2 |   53026.11 |  3022.88 |
cusparse/generic                              (3) |    81.94 |   0.05 |  0.1 |       6.52 |   192.00 |   2.07 |  2.5 |    5151.40 |  2696.02 |
device/ldg                                    (7) |    18.45 |   0.00 |  0.0 |       0.00 |   380.00 |   0.75 |  4.1 |    1648.80 |  3288.11 |
device/intrinsics                             (5) |    66.59 |   0.00 |  0.0 |       0.00 |   448.00 |   2.66 |  4.0 |    6301.93 |  3040.01 |
cusparse/linalg                               (2) |   112.89 |   0.01 |  0.0 |     650.83 |   320.00 |   6.06 |  5.4 |   24957.58 | 14625.85 |
cusparse/interfaces                           (6) |   129.88 |   0.09 |  0.1 |      10.74 |   192.00 |   3.48 |  2.7 |    8193.08 |  3338.67 |
device/intrinsics/memory                      (5) |    42.96 |   0.00 |  0.0 |       0.02 |   124.00 |   1.76 |  4.1 |    3656.19 |  3173.60 |
sorting                                       (8) |   283.36 |   0.02 |  0.0 |     543.84 |   876.00 |   9.28 |  3.3 |   26815.55 |  9123.87 |
device/random                                 (9) |    93.20 |   0.00 |  0.0 |       0.17 |   124.00 |   3.51 |  3.8 |    7610.02 |  3234.78 |
device/intrinsics/output                      (2) |    50.13 |   0.00 |  0.0 |       0.00 |   252.00 |   1.95 |  3.9 |    4272.94 | 14625.85 |
device/intrinsics/math                        (7) |    95.85 |   0.00 |  0.0 |       0.00 |   400.00 |   3.91 |  4.1 |    8523.19 |  3288.11 |
device/intrinsics/atomics                     (3) |   118.59 |   0.00 |  0.0 |       0.00 |   124.00 |   4.85 |  4.1 |   12379.01 |  2903.20 |
cusolver/dense                                (4) |   266.33 |   0.13 |  0.0 |    2480.20 |  1532.00 |  11.11 |  4.2 |   26306.00 |  3986.15 |
device/intrinsics/wmma                        (6) |   112.69 |   0.01 |  0.0 |       0.63 |   126.00 |   4.99 |  4.4 |   14439.90 |  3338.67 |
Testing finished in 17 minutes, 51 seconds, 531 milliseconds

Test Summary: |  Pass  Broken  Total  Time
  Overall     | 17020       5  17025      
    SUCCESS
     Testing CUDA tests passed

**Comment by bjarthur** [comment]
glad it works, and good to see you've upgraded to the latest version of TrainSpikingNet too!

**Comment by russelljjarvis** [comment]
> There is https://github.com/JuliaPackaging/Scratch.jl

Do you think it would be easy to implement here?

**Comment by bjarthur** [comment]
a new commit now deletes the scratch folder when testing

**Comment by russelljjarvis** [comment]
That is really awesome too!
